### PR TITLE
Prevent exception with localStorage.getItem

### PR DESCRIPTION
**Pull request by ccallebs**
On our production application, Honeybadger reported some clients are experiencing an exception with `localStorage.getItem` in this script. This fixes that.

### CODE REVIEW

**Comment by cubiq** [comment]
exception on getItem? would like to know more about that

**Comment by ccallebs** [comment]
Browser: `Mozilla/5.0 (Linux; U; Android 4.3; id-; SM-N750 Build/JSS15J) AppleWebKit/534.24 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.24 T5/2.0 bdbrowser_i18n/4.5.0.6`

The exceptions we're encountering:

"Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

and

"Cannot call method 'getItem' of null"

**Comment by ccallebs** [comment]
I should note, it's only happening on a small subset of our requests. Maybe 20 in the last day, out of thousands.

**Comment by ccallebs** [comment]
@cubiq Update for this. It's ran on our production servers over the weekend and the errors above have stopped occurring. Let me know if you need any more information.

**Comment by cubiq** [comment]
I believe your solution still misses something to be 100% fail safe on the ATH.

You should probably set the `ath.hasLocalStorage = false;` to say the least, otherwise ATH simply thinks that the session has not been set yet.

**Comment by ccallebs** [comment]
@cubiq Gotcha. I can add that in. I'm not familiar with the codebase all that well, my goal was just to stop the exceptions. I'll give it another pass and post here when done.

**Comment by ccallebs** [comment]
@cubiq Anything else you need me to do on this? Or should I close the PR?

**Comment by cubiq** [comment]
working on it later today

**Comment by ccallebs** [comment]
@cubiq Just pinging you about this.

**Pull request merged**
