### PR TITLE
Danish and PNG opimizations

### PR DESCRIPTION
**Pull request by rbu**
A language update and lossless PNG recompressions. Hope you can merge this and it's useful to you.

### CODE REVIEW

**Comment by cubiq** [comment]
what tool did you use to optimize the PNG?

**Comment by dhunink** [comment]
@cubiq just a related note: I'm always comprising images with https://imageoptim.com (multiple times). The result is awesome and acknowledge by Google Pagespeed Insights!

**Comment by rbu** [comment]
I'm using this script. Unfortunately, it will change files even if they keep their size. I'm guessing imageoptim is a better choice if you have a mac.

```
# Requires optipng http://optipng.sourceforge.net/
# and the advancecomp tools http://advancemame.sourceforge.net/comp-readme.html
find -iname '*.png' \
  -exec optipng -o7 -zm1-9 "{}" + \
  -exec advdef --shrink-insane --recompress "{}" + \
  -exec advpng --shrink-insane --recompress "{}" + \
  -exec optipng -o7 -zm1-9 "{}" + \
  -exec advdef --shrink-insane --iter 15 --recompress "{}" + \
  -exec advpng --shrink-insane --iter 25 --recompress "{}" +
```

**Comment by cubiq** [comment]
insane! :) thanks for sharing

**Pull request merged**
