### PR TITLE
improve Japanese message

### PR DESCRIPTION
**Pull request by AtsushiSakai**
I improved and added Japanese message on the ATH button.
I feel it is better expression for Japanese native speaker.

### CODE REVIEW

**Comment by grizzly** [comment]
Ich bin bis einschließlich 26. Juli 2015 auf Urlaub und daher in dieser Zeit nicht erreichbar.
I am out of office until 26th of June 2015.

Die eMails werden nicht automatisch weitergeleitet.
The emails will not be forwarded.

Für technische Fragen / technical questions:
Stefan Gsottbauer, +43 316 298202-13, st.gsottbauer@grizzly.cc
 
Für kaufmännische Fragen / commercial questions:
Mag. Nikolaus Grissmann, +43 298202-10, n.grissmann@grizzly.cc

Mit freundlichen Grüßen / Kind regards

Stefan Mayr

**Comment by cubiq** [comment]
would you check against the latest version and update the PR? thanks!

**Comment by AtsushiSakai** [comment]
I updated my PR!!

**Comment by cubiq** [comment]
I'm really sorry to have to ask you again, but it seems your PR got behind some of the recent updates...

**Comment by AtsushiSakai** [comment]
I updated my PR again!!

**Comment by cubiq** [comment]
updated... but... ahem... it needs fixing :P

**Comment by AtsushiSakai** [comment]
Oh.. I'm sorry. It's my mistake.

**Comment by cubiq** [comment]
please fix asap, thanks

**Pull request merged**
