### PR TITLE
Fixed markup replacement

### PR DESCRIPTION
**Pull request by szikszail**
Hi,

I have created this fix, because in the current version the components puts the markup directly into the *html* element and not into the *body* element.

### CODE REVIEW

**Comment by szikszail** [comment]
@cubiq could you check it and make a new release?

**Comment by cubiq** [comment]
gosh I really don't remember why I put it into the documentElement, but I swear there was a good reason...

**Comment by szikszail** [comment]
@cubiq I don't want to push you, but do you see any objection to merge and close this PR?

**Comment by RogerE** [comment]
This change makes the popup stop working for me. Because, if I understand things correctly, when you load the script in the header(like in the demos) body does not exist in the DOM yet?

**Pull request merged**
